from armour.legacy.bernstein_to_poly import bernstein_to_poly
from armour.legacy.match_deg5_bernstein_coefficients import match_deg5_bernstein_coefficients
from armour.legacy.StraightLineHLP import StraightLineHLP