name: documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser
          ssh-agent sh -c 'echo "${{ secrets.ZONOPY_KEY }}" | ssh-add - && git clone git@github.com:roahmlab/zonopy.git'
          cd zonopy && pip install -e . && cd ..
          ssh-agent sh -c 'echo "${{ secrets.ZONOPYROB_KEY }}" | ssh-add - && git clone git@github.com:roahmlab/zonopy-robots.git'
          cd zonopy-robots && pip install -e . && cd ..
          pip install -e .
      - name: Sphinx build
        run: |
          sphinx-build docs/source docs/build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true